#! /bin/bash
## Loger script

# get time
time="`date +%H%M`"
timestamp="`date +%s`"
timestamp+="|"
# get 15 min load
load="`cat /proc/loadavg | head -c 15 | tail -c 5`"
log=$timestamp$load
echo $log > tmp.txt
# create log file if not present
if [ ! -f log.txt ]; then
    touch log.txt
fi
# clear 1 week old log if midnight
if [ "$time" -lt 1 ]; then
  head -n 692 log.txt >> tmp.txt
else
# otherwise just add the new log
  cat log.txt >> tmp.txt
fi 
mv tmp.txt log.txt
